spring:
  application:
    name: zuul-server
server:
  port: 8769
#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#配置路由规则
zuul:
  routes:
    service-hi:
      path: /hi
      serviceId: service-hi
    service-feign:
      path: /hi
      serviceId: service-feign
